version: '3.9'

services:
  accuknox_social_app:
    container_name: accuknox_social_app
    build: .
    ports: 
      - "8000:8000"
    environment:
      - DB_NAME=postgres_accuknox_social
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_accuknox_social
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dummy_user@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  pgdata: {}
    
